Repository StackStorm/hubot-stackstorm, pull requests merged in 2019-06, with the labels that each got.

#172 Exit hubot on unhandled promise rejections and other unrecoverable errors
  CHANGELOG.rst
  scripts/stackstorm.js
Labels: RFR, bug

#179 Enable testing Node.js 11 and 12, but allow them to fail
  .travis.yml
Labels: enhancement

#178 Exit hubot on Unauthorized errors
  CHANGELOG.rst
  package.json
  scripts/stackstorm.js
  tests/test-st2-unauthorized.js
Labels: bug, tests

#183 Don't consider failed alias execution as a critical reason to exit hubot
  CHANGELOG.rst
  package.json
  scripts/stackstorm.js
Labels: bug, regression

#180 Move babel-eslint to devDependencies instead of dependencies
  CHANGELOG.rst
  package.json
Labels: enhancement
