Repository StackStorm/hubot-stackstorm, pull requests merged in 2020-04, with the labels that each got.

#200 Fix issue with webex adapter
  src/lib/adapters/spark.js
  src/lib/stackstorm_api.js
Labels: adapter: Cisco Spark, bug

#201 Fix tests
  package.json
  test/test-formatdata.js
  test/test-postdata.js
Labels: adapter: Cisco Spark, bug, regression, tests

#203 Update st2client.js to 1.2.2
  CHANGELOG.rst
  package-lock.json
  package.json
Labels: dependency issue, security
